In [25]:
import numpy as np

#Matriz que define al patron + como entrada
img_entrada = np.array([[0, 0, 0],
                        [1, 1, 1],
                        [0, 1, 0]])

#Definicion de los vectores para los pesos
#en lienas horizontales y verticales
pesos_horizontales = np.array([[-1, -1, -1],
                               [1, 1, 1],
                               [-1, -1, -1]])

pesos_verticales = np.array([[-1, 1, -1],
                             [-1, 1, -1],
                             [-1, 1, -1]])

def fn_activacion(x):
  return np.heaviside(x,0.5)

def celda_s(img_entrada, pesos):
  entrada_neta = np.dot(pesos.flatten(), img_entrada.flatten())
  print(entrada_neta)
  salida = fn_activacion(entrada_neta)
  return salida.reshape(1)

def celda_c(s_salida_horizontal, s_salida_vertical):
  vector_ent = np.concatenate([s_salida_horizontal, s_salida_vertical])
  entarda_neta = np.dot(vector_ent, np.array([-0.5,1]))
  salida = fn_activacion(entarda_neta)
  return salida

#Cálculo de la salida de una celda S
s_salida_horizontal = celda_s(img_entrada[:3, :], pesos_horizontales)
s_salida_vertical = celda_s(img_entrada[: , :3], pesos_verticales)

#Cálculo de la salida C
salida_c = celda_c(s_salida_horizontal, s_salida_vertical)

#Salidas
print("Imagen de entrada:\n",img_entrada)
print("Salida de celda S horizontal:\n", s_salida_horizontal)
print("Salida de celda S vertical:\n", s_salida_vertical)
print("Salida de celda C:\n",salida_c)

-3
-1
Imagen de entrada:
 [[0 1 0]
 [1 1 1]
 [0 1 0]]
Salida de celda S horizontal:
 [0.]
Salida de celda S vertical:
 [0.]
Salida de celda C:
 0.5


In [ ]:


img_entrada_4 = np.array([[0, 0, 1, 0, 0, 1, 0, 0],
                          [0, 0, 1, 0, 0, 1, 0, 0],
                          [0, 0, 1, 0, 0, 1, 0, 0],
                          [0, 0, 1, 1, 1, 1, 0, 0],
                          [0, 0, 0, 0, 0, 1, 0, 0],
                          [0, 0, 0, 0, 0, 1, 0, 0],
                          [0, 0, 0, 0, 0, 1, 0, 0],
                          [0, 0, 0, 0, 0, 1, 0, 0]])


img_entrada_9 = np.array([[0, 0, 1, 1, 1, 1, 0, 0],
                          [0, 0, 1, 0, 0, 1, 0, 0],
                          [0, 0, 1, 0, 0, 1, 0, 0],
                          [0, 0, 1, 1, 1, 1, 0, 0],
                          [0, 0, 0, 0, 0, 1, 0, 0],
                          [0, 0, 0, 0, 0, 1, 0, 0],
                          [0, 0, 0, 0, 0, 1, 0, 0],
                          [0, 0, 0, 0, 0, 1, 0, 0]])


img_entrada_0 = np.array([[0, 0, 1, 1, 1, 1, 0, 0],
                        [0, 0, 1, 0, 0, 1, 0, 0],
                        [0, 0, 1, 0, 0, 1, 0, 0],
                        [0, 0, 1, 0, 0, 1, 0, 0],
                        [0, 0, 1, 0, 0, 1, 0, 0],
                        [0, 0, 1, 0, 0, 1, 0, 0],
                        [0, 0, 1, 0, 0, 1, 0, 0],
                        [0, 0, 1, 1, 1, 1, 0, 0]])

img_entrada_1 = np.array([[0, 0, 0, 1, 1, 0, 0, 0],
                          [0, 0, 1, 0, 1, 0, 0, 0],
                          [0, 1, 0, 0, 1, 0, 0, 0],
                          [0, 0, 0, 0, 1, 0, 0, 0],
                          [0, 0, 0, 0, 1, 0, 0, 0],
                          [0, 0, 0, 0, 1, 0, 0, 0],
                          [0, 0, 0, 0, 1, 0, 0, 0],
                          [0, 0, 1, 1, 1, 1, 1, 0]])



#Definicion de los vectores para los pesos
#en lienas horizontales y verticales
pesos_horizontales =

pesos_verticales =

def fn_activacion(x):
  return np.heaviside(x,0.5)

def escalon(x,theta):
    return 1 if x > theta else 0

def celda_s(img_entrada, pesos):
  entrada_neta = np.dot(pesos.flatten(), img_entrada.flatten())
  print(entrada_neta)
  salida = fn_activacion(entrada_neta)
  return salida.reshape(1)

def celda_c(s_salida_horizontal, s_salida_vertical):
  vector_ent = np.concatenate([s_salida_horizontal, s_salida_vertical])
  entarda_neta = np.dot(vector_ent, np.array([1,1]))
  salida = escalon(entarda_neta,1)
  return salida

img_entrada = img_entrada_1

#Cálculo de la salida de una celda S
s_salida_horizontal = celda_s(img_entrada[:8, :], pesos_horizontales)
s_salida_vertical = celda_s(img_entrada[: , :8], pesos_verticales)

#Cálculo de la salida C
salida_c = celda_c(s_salida_horizontal, s_salida_vertical)

#Salidas
print("Imagen de entrada:\n",img_entrada)
print("Salida de celda S horizontal:\n", s_salida_horizontal)
print("Salida de celda S vertical:\n", s_salida_vertical)
print("Salida de celda C:\n",salida_c)

-2.0
-11
Imagen de entrada:
 [[0 0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0 0]
 [0 1 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 1 1 1 1 1 0]]
Salida de celda S horizontal:
 [0.]
Salida de celda S vertical:
 [0.]
Salida de celda C:
 0
